# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jjosephi <jjosephi@student.42.us.org>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/05/14 04:57:09 by jjosephi          #+#    #+#              #
#    Updated: 2020/05/14 04:57:09 by jjosephi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= convert

all : $(NAME)

$(NAME) :
	clang++ -Wall -Wextra -Werror main.cpp -o convert

fclean :
	rm -f $(NAME)

re : fclean $(NAME)
